name: Send Release Notes to Slack

on:
  release:
    types: [published]

jobs:
  send_to_slack:
    name: Send Release Notes to Slack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Extract Release Notes
        id: extract_release_notes
        uses: ffurrer2/extract-release-notes@v2

      - name: Extract version number
        id: extract_version_number
        run: |
          version=$(jq -r '.version' package.json)
          echo "version=$version" >> $GITHUB_ENV

      - name: Send to Slack
        run: |
          # Clean and format the release notes for Slack
          NOTES=$(echo "${{ steps.extract_release_notes.outputs.release_notes }}" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g')
          
          # Build JSON payload for Slack (use proper newlines and formatting)
          payload=$(cat <<EOF
          {
            "text": ":tada: *New Release Published!*\n*Version:* ${version}\n\n*Release Notes:*\n${NOTES}"
          }
          EOF
          )

          # Send the payload to Slack webhook
          curl -X POST -H "Content-type: application/json" --data "$payload" "$SLACK_WEBHOOK_URL"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
